/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MainGV.SuaDiem;

import DB.ConnectDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author anho2
 */
public class SuaDiem extends javax.swing.JFrame {

    /**
     * Creates new form SuaDiem
     */
    private JFrame parentFrame;
    private String MSSV;
    private String MaLop;
    
    public SuaDiem(JFrame parentFrame,String MSSV,String MaLop) {
        initComponents();
        this.parentFrame = parentFrame;
        this.MSSV = MSSV;
        this.MaLop = MaLop;
        XemTT();
    }

    Connection con = null;  // Khai báo kết nối
    PreparedStatement pst = null; // Khai báo PreparedStatement
    
    private void XemTT(){     
        MSSV1.setEditable(false);
        MSSV1.setFocusable(false);  // Không thể chọn hoặc tương tác
        try{
            con = ConnectDB.getConnection();
            pst = con.prepareStatement("""
                             Select s.HoTen, d.Diem
                             From diemsv d
                             natural join lophoc l
                             natural join sv s
                             where l.MaLop = ?
                             and s.MSSV = ? """);
            pst.setString(1, MaLop);
            pst.setString(2, MSSV);
            ResultSet rs = pst.executeQuery();
            MSSV1.setText(MSSV);
            if(rs.next()){
                String Ten,Diem;
                Ten = rs.getString(1);
                Diem = rs.getString(2);                
                Name1.setText(Ten);
                Score1.setText(Diem);
            }
            
        }   catch(SQLException ex){
            Logger.getLogger(SuaDiem.class.getName () ) .log (Level. SEVERE, null, ex) ;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Huy = new javax.swing.JButton();
        OK = new javax.swing.JButton();
        MSSV1 = new javax.swing.JTextField();
        Name1 = new javax.swing.JTextField();
        Score1 = new javax.swing.JTextField();
        MSSV11 = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Score = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 204));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        Huy.setBackground(new java.awt.Color(255, 51, 0));
        Huy.setText("Huỷ");
        Huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HuyActionPerformed(evt);
            }
        });

        OK.setBackground(new java.awt.Color(0, 255, 102));
        OK.setText("Cập nhật điểm");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        MSSV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MSSV1ActionPerformed(evt);
            }
        });

        Name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Name1ActionPerformed(evt);
            }
        });

        MSSV11.setText("MSSV");

        Name.setText("Họ Tên");

        Score.setText("Điểm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Name, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(MSSV11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Score, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Score1)
                    .addComponent(Name1)
                    .addComponent(MSSV1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Huy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(OK)))
                .addGap(73, 73, 73))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MSSV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MSSV11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Name))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Score1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Score))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Huy)
                    .addComponent(OK))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HuyActionPerformed
        // TODO add your handling code here:
        dispose();
        parentFrame.setEnabled(true);
        parentFrame.setVisible(true);
    }//GEN-LAST:event_HuyActionPerformed

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        // TODO add your handling code here:
        String HoTen = Name1.getText();
        String Diem = Score1.getText();
        ResultSet rs=null;
        try {
            con = ConnectDB.getConnection();
            pst = con.prepareStatement("""
                             UPDATE diemsv
                             SET Diem = ?
                             WHERE MSSV = ? AND MaLop = ?;""");
            pst.setString(1, Diem);
            pst.setString(2, MSSV);
            pst.setString(3, MaLop);
            pst.executeUpdate();
            pst = con.prepareStatement("""
                             UPDATE sv
                             SET HoTen =  ? 
                             WHERE MSSV = ?;""");
            pst.setString(1, HoTen);
            pst.setString(2, MSSV);
            pst.executeUpdate();
            
        }   catch (SQLException e) {
                // Xử lý lỗi nếu có
                e.printStackTrace();
                }finally {
                // Đảm bảo đóng kết nối và các đối tượng sử dụng sau khi xong
                try {
                    if (rs != null) rs.close();
                    if (pst != null) pst.close();
                    if (con != null) con.close();
                } catch (SQLException se) {
                    se.printStackTrace();
                }
            }
        
        dispose();
        parentFrame.setEnabled(true);
        parentFrame.setVisible(true);
    }//GEN-LAST:event_OKActionPerformed

    private void MSSV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MSSV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MSSV1ActionPerformed

    private void Name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Name1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Huy;
    private javax.swing.JTextField MSSV1;
    private javax.swing.JLabel MSSV11;
    private javax.swing.JLabel Name;
    private javax.swing.JTextField Name1;
    private javax.swing.JButton OK;
    private javax.swing.JLabel Score;
    private javax.swing.JTextField Score1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
