/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SearchHS;

import DB.ConnectDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anho2
 */
public class HSHome extends javax.swing.JFrame {
    private String MSSV;
    /**
     * Creates new form HSMain
     */
    public HSHome(String MSSV) {
        this.MSSV = MSSV;
        initComponents();
        XemDiem();
    }
    public void setMSSV(String MSSV) {
        this.MSSV = MSSV;
    }
    public String getMSSV() {
        return MSSV;
    }
    Connection con = null;  // Khai báo kết nối
    PreparedStatement pst = null; // Khai báo PreparedStatement
    private void XemDiem() {
        // TODO add your handling code here:       
        ResultSet rs = null;
        PreparedStatement pst = null;
        jTable1.setModel(new DefaultTableModel());
        setTitle("MSSV: "+MSSV);
        try {
            // Kết nối đến cơ sở dữ liệu
                con = ConnectDB.getConnection();
                
                String sql = """
                             Select l.MaLop, l.MaMon, l.TenMon, d.Diem
                             From diemsv d
                             natural join lophoc l
                             natural join sv s
                             where s.MSSV = ?""";
                pst= con.prepareStatement(sql);
                pst.setString(1, MSSV);
                rs = pst.executeQuery();                
                ResultSetMetaData rsmd= rs.getMetaData();
                DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
                int cols = rsmd.getColumnCount();
                String[] colName = new String[cols];
                for(int i=0;i<cols;i++){
                    colName[i]=rsmd.getColumnName(i+1);
                }
                model.setColumnIdentifiers(colName);
                String MaLop,MaMon,TenMon,Diem;
                while(rs.next()){
                    MaLop=rs.getString(1);
                    MaMon=rs.getString(2);
                    TenMon=rs.getString(3);
                    Diem=rs.getString(4);
                    String[] row={MaLop,MaMon,TenMon,Diem};
                    model.addRow(row);
                }
                pst.close();
                con.close();
                
        }   catch (SQLException e) {
                // Xử lý lỗi nếu có
                e.printStackTrace();
                }finally {
                // Đảm bảo đóng kết nối và các đối tượng sử dụng sau khi xong
                try {
                    if (rs != null) rs.close();
                    if (pst != null) pst.close();
                    if (con != null) con.close();
                } catch (SQLException se) {
                    se.printStackTrace();
                }
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
