/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Login;

import Login.swinglocal.Button;
import Login.swinglocal.MyPasswordField;
import Login.swinglocal.MyTextField;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JLabel;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author anho2
 */
public class PanelLogin extends javax.swing.JLayeredPane {

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    
    public String getMSSV() {
        return MSSV;
    }

    // Setter cho MSSV
    public void setMSSV(String MSSV) {
        this.MSSV = MSSV;
    }
    
    private String user;
    private String password;
    public String MSSV;
    
    /**
     * Creates new form PanelCover
     */
    public PanelLogin(ActionListener eventHS,ActionListener eventGV) {
        initComponents();
        initHS(eventHS);
        initGV(eventGV);
        GV.setVisible(false);
        HS.setVisible(true);
    }
    private void initHS(ActionListener eventHS){
        HS.setLayout(new MigLayout("wrap", "push[center]push", "push[]25[]10[]10[]25[]push"));
        JLabel label = new JLabel("Vui lòng nhập MSSV");
        label.setFont(new Font("sansserif", 1, 30));
        label.setForeground(new Color(7,146,121));
        HS.add(label);
        
        MyTextField txtMSSV = new MyTextField();
        txtMSSV.setHint("MSSV");
        HS.add(txtMSSV, "w 60%");
        
        Button cmd = new Button();
        cmd.setBackground(new Color(7,146,121));
        cmd.setForeground(new Color(250,250,250));
        cmd.addActionListener(eventHS);
        cmd.setText("Tra cứu");
        HS.add(cmd , "w 40%, h 40");
        cmd.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                String MSSV = txtMSSV.getText().trim();
                setMSSV(MSSV);
            }
        });
        
    }
    
    private void initGV(ActionListener eventGV){
        GV.setLayout(new MigLayout("wrap", "push[center]push", "push[]25[]10[]10[]25[]push"));
        JLabel label = new JLabel("Vui lòng đăng nhập");
        label.setFont(new Font("sansserif", 1, 30));
        label.setForeground(new Color(7,146,121));
        GV.add(label);
        
        MyTextField txtUser = new MyTextField();
        txtUser.setHint("Tên đăng nhập");
        GV.add(txtUser, "w 60%");
        MyPasswordField txtPass = new MyPasswordField();
        txtPass.setHint("Mật khẩu");
        GV.add(txtPass, "w 60%");
        
        Button cmd = new Button();
        cmd.setBackground(new Color(7,146,121));
        cmd.setForeground(new Color(250,250,250));
        cmd.addActionListener(eventGV);
        cmd.setText("Đăng nhập");
        GV.add(cmd , "w 40%, h 40");
        cmd.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                String user = txtUser.getText().trim();
                String password = String.valueOf(txtPass.getPassword());
                setUser(user);
                setPassword(password);
            }
        });

//        cmd.addActionListener(new ActionListener() {
//        @Override
//        public void actionPerformed(ActionEvent e) {
//            // Lấy giá trị từ các trường văn bản
//            String username = txtUser.getText();
//            String password = new String(txtPass.getPassword());  // Lấy mật khẩu từ MyPasswordField
//            
//            // Kiểm tra thông tin đăng nhập hoặc thực hiện hành động khác
//            if (username.equals("admin") && password.equals("admin123")) {
//                JOptionPane.showMessageDialog(null, "Đăng nhập thành công!");
//            } else {
//                JOptionPane.showMessageDialog(null, "Sai tên đăng nhập hoặc mật khẩu!");
//            }
//        }
//    });
        }
    
    public void showHS(boolean show){
        if(show){
            HS.setVisible(true);
            GV.setVisible(false);
        }   else{
            HS.setVisible(false);
            GV.setVisible(true);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GV = new javax.swing.JPanel();
        HS = new javax.swing.JPanel();

        setLayout(new java.awt.CardLayout());

        GV.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout GVLayout = new javax.swing.GroupLayout(GV);
        GV.setLayout(GVLayout);
        GVLayout.setHorizontalGroup(
            GVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        GVLayout.setVerticalGroup(
            GVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        add(GV, "card3");

        javax.swing.GroupLayout HSLayout = new javax.swing.GroupLayout(HS);
        HS.setLayout(HSLayout);
        HSLayout.setHorizontalGroup(
            HSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        HSLayout.setVerticalGroup(
            HSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        add(HS, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GV;
    private javax.swing.JPanel HS;
    // End of variables declaration//GEN-END:variables



}
