/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Login;

import swinglocal.ButtonOutLine;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GradientPaint;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import javax.swing.JLabel;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author anho2
 */
public class PanelCover extends javax.swing.JPanel {

    /**
     * Creates new form PanelCover
     */
    private final DecimalFormat df =new DecimalFormat("##0.###");
    private ActionListener event;
    private MigLayout layout;
    private JLabel title;
    private JLabel description;
    private JLabel description1;
    private ButtonOutLine button;
    private boolean isLogin;
    
    public PanelCover() {
        initComponents();
        setOpaque(false);
        layout = new MigLayout("wrap, fill", "[center]", "push[]25[]25[]push");
        setLayout(layout);
        init();
    }
    private void init(){
        title=new JLabel("WELCOME");
        title.setFont(new Font("sansserif", 1, 30));
        title.setForeground(new Color(245, 245, 245));
        add(title);
        description = new JLabel("NHẬP MÃ SỐ SINH VIÊN");
        description.setForeground(new Color(245, 245, 245));
        add(description);
        description1 = new JLabel("ĐỂ TRA CỨU ĐIỂM");
        description1.setForeground(new Color(245, 245, 245));
        add(description1);
        button=new ButtonOutLine();
        button.setBackground(new Color(255,255,255));
        button.setForeground(new Color(255,255,255));
        button.setText("Bạn là Giáo Viên?");
        button.addActionListener(new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent ae) {
                event.actionPerformed(ae);
           }
        });
        add(button,"w 50%, h 40");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics grphcs){
        Graphics2D g2=(Graphics2D) grphcs;    
        GradientPaint  gra= new GradientPaint(0,0,new Color(10, 254, 250),0,getHeight(),new Color(63, 173, 188));
        g2.setPaint(gra);
        g2.fillRect(0,0,getWidth(),getHeight());        
        super.paintComponent(grphcs);
        
    }
    
    public void addEvent(ActionListener event){
        this.event=event;
        
    }
    
    public void HSLeft(double v){
        v=Double.valueOf(df.format(v));
        login(false);
        layout.setComponentConstraints(title, "pad 0 -" + v + "% 0 0");
        layout.setComponentConstraints(description, "pad 0 -" + v + "% 0 0");
        layout.setComponentConstraints(description1, "pad 0 -" + v + "% 0 0");
        
    }
    public void HSRight(double v){
        v=Double.valueOf(df.format(v));
        login(false);
        layout.setComponentConstraints(title, "pad 0 -" + v + "% 0 0");
        layout.setComponentConstraints(description, "pad 0 -" + v + "% 0 0");
        layout.setComponentConstraints(description1, "pad 0 -" + v + "% 0 0");
        
    }
    public void GVLeft(double v){
        v=Double.valueOf(df.format(v));
        login(true);
        layout.setComponentConstraints(title, "pad 0 " + v + "% 0 "+v+ "%");
        layout.setComponentConstraints(description, "pad 0 " + v + "% 0 "+v+ "%");
        layout.setComponentConstraints(description1, "pad 0 " + v + "% 0 "+v+ "%");
    }
    public void GVRight(double v){
        v=Double.valueOf(df.format(v));
        login(true);
        layout.setComponentConstraints(title, "pad 0 " + v + "% 0 "+v+ "%");
        layout.setComponentConstraints(description, "pad 0 " + v + "% 0 "+v+ "%");
        layout.setComponentConstraints(description1, "pad 0 " + v + "% 0 "+v+ "%");
    }
    
    private void login(boolean login){
        if(this.isLogin != login)   {
            if(login){
                title.setText("GIÁO VIÊN");
                description.setText("ĐĂNG NHẬP VÀO TÀI KHOẢN");
                description1.setText("ĐỂ THỰC HIỆN CHỈNH SỬA");
                button.setText("Bạn là Học Sinh?");
            }   else{
                title.setText("HỌC SINH");
                description.setText("NHẬP MÃ SỐ SINH VIÊN");
                description1.setText("ĐỂ TRA CỨU ĐIỂM");
                button.setText("Bạn là Giáo Viên?");
            }
            this.isLogin =login;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
